# Generated by Django 4.2.7 on 2023-11-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio',
            field=models.FileField(default=1, upload_to='musics/'),
            preserve_default=False,
        ),
    ]
