# Generated by Django 4.2.7 on 2023-11-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_music_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio',
            field=models.FileField(upload_to='musics'),
        ),
    ]
