# Generated by Django 4.2.7 on 2023-11-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_musics'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
